memorystore.host: localhost
memorystore.port: 6379

supply-config:
 auth:
    url: https://test.api.amadeus.com/v1/security/oauth2/token
    client-id: lV1tENnMOqpujUKObc2x2fQ7zHASAntf
    client-secret: 4pQA5koPq9skYODw
    grant-type: client_credentials
 base-url: https://test.api.amadeus.com/v1/
 travel-restrictions: duty-of-care/diseases/covid19-area-report

spring:
  datasource:
     url: jdbc:h2:mem:testdb
     driverClassName: org.h2.Driver
     username: sa
     password: password
  jpa:
     database-platform: org.hibernate.dialect.H2Dialect
  h2:
     console:
       enabled: true