insert into COVID_SURVEY(id,name,source,destination,COVID_REVIEW,recommend) values (1,'Anonymous','US','FR','Today, my family and I successfully used our CDC vaccination cards at the Louvre and the Eiffel Tower. They require you to have your passport with the card as they check the name on the card against the passport and look at you picture. I saw a couple in front of me at the Eiffel Tower denied admission because they did not have their passports. Note that a new rule was effective on 7/30 that requires USA citizens to get some type of paperwork from the US Embassy in order to get a digital Pass Sanitaire. There are long lines at local pharmacies with French nationals getting their Pass Sanitaires. I don’t believe the government wants to add to the pharmacy workloads with tourists. The US Embassy paperwork is likely aimed to limit Pass Sanitaires to US citizens who are in France for longer than just a vacation',false);

insert into COVID_SURVEY(id,name,source,destination,COVID_REVIEW,recommend) values (2,'Anne Fowler','UK','FR','Me and my family travelled to France a couple of weeks back. We were fully vaccinated and were not required to present any forms, or negative COVID tests to enter French territory, but proof of vaccination status had to be presented at border controls.
Also there was no required quarantine upon arrival in France.',true);

insert into COVID_SURVEY(id,name,source,destination,COVID_REVIEW,recommend) values (3,'Luke Skywalker','US','DE','Hi folks,
Travelled to Germany recently for a personal trip. Germany has lifted restrictions soon so that tourism can be encouraged.
These relaxations apply to people who have fully vaccinated themselves or have recovered from coronavirus.
Recommended to plan a trip maybe in July or August as it might be too soon to say whether places will open or not.',true);

insert into COVID_SURVEY(id,name,source,destination,COVID_REVIEW,recommend) values (4,'Mark Hamil','US','FR','France has been witnessing a steady decline in coronavirus infections. Therefore, the local authorities are easing the restrictions so that tourists can visit the most popular tourist country.
Here, life has returned to normal, although people are still abiding by the protocols in schools, shops, restaurants, and so on.
If you decide to go then be aware to have a mask with you if around others, even if vaccinated. I think this will be case until each place has herd immunity (75-80% of population vaccinated).',true);

insert into COVID_SURVEY(id,name,source,destination,COVID_REVIEW,recommend) values (5,'Georgina','US','FR','We are currently in Paris. Our CDC cards were excepted into the Louvre, Orangerie, Catacombs, Sainte Chapelle, and Versailles. Every restaurant except McDonald''s (we were trying to purchase water) has accepted our CDC card. We have also been on trains and they have accepted our CDC card.',true);